# Generated by Django 5.2.6 on 2025-11-21 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0005_tvshow_title_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesong',
            name='genre',
        ),
    ]
