# Generated by Django 5.0.6 on 2025-01-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_song_created_on_alter_song_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopSong',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('songs.song',),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('name', 'artist'), name='unique_song_per_artist'),
        ),
    ]
