# Generated by Django 5.1.4 on 2025-03-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_song_spotify_avatar_remove_song_spotify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist_name',
        ),
        migrations.AddField(
            model_name='artist',
            name='birthname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, help_text="The artist's stage name", max_length=100, null=True, unique=True),
        ),
    ]
