# Generated by Django 5.0.6 on 2025-01-03 11:23

import songs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_popsong_song_unique_song_per_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapSong',
            fields=[
            ],
            options={
                'ordering': ['artist'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('songs.song',),
        ),
        migrations.AlterModelOptions(
            name='popsong',
            options={'ordering': ['artist']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['artist']},
        ),
        migrations.AddField(
            model_name='song',
            name='difficulty',
            field=models.PositiveIntegerField(default=1, validators=[songs.validators.validate_difficulty]),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(condition=models.Q(('difficulty', 5)), fields=['difficulty'], name='diffulty_hard'),
        ),
    ]
