# Generated by Django 5.0.6 on 2025-01-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_rapsong_alter_popsong_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='diffulty_hard',
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(condition=models.Q(('difficulty__gte', 5)), fields=['difficulty'], name='diffulty_hard'),
        ),
    ]
