# Generated by Django 5.0.6 on 2025-01-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_remove_song_diffulty_hard_song_diffulty_hard'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='song',
            name='diffulty_hard',
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(condition=models.Q(('difficulty', 4), ('difficulty', 5), _connector='OR'), fields=['difficulty'], name='diffulty_hard'),
        ),
    ]
