# Generated by Django 5.0.6 on 2025-01-03 11:25

import songs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_remove_song_diffulty_hard_song_diffulty_hard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='difficulty',
            field=models.IntegerField(default=1, validators=[songs.validators.validate_difficulty]),
        ),
    ]
