# Generated by Django 5.2.6 on 2025-11-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_popartist_rapartist_alter_artist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfroSong',
            fields=[
            ],
            options={
                'verbose_name': 'afro song',
                'ordering': ['artist'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('songs.song',),
        ),
    ]
