# Generated by Django 5.2.6 on 2025-11-21 19:58

import blindtest.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_afrosong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='difficulty',
            field=models.IntegerField(default=1, validators=[blindtest.validators.validate_difficulty]),
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.PositiveIntegerField(default=0, validators=[blindtest.validators.validate_year]),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='The YouTube video ID for the theme song', max_length=150, null=True),
        ),
    ]
