# Generated by Django 5.0.6 on 2025-01-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_song_youtube_id_alter_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='youtube',
        ),
    ]
