# Generated by Django 5.0.6 on 2025-01-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_remove_song_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='spotify_avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify_id',
            field=models.CharField(blank=True, help_text='ID for the given artist on Spotify', max_length=100, null=True),
        ),
    ]
