# Generated by Django 5.0.6 on 2025-01-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_song_spotify_avatar_song_spotify_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('spotify_id', models.CharField(blank=True, help_text='ID for the given artist on Spotify', max_length=100, null=True)),
                ('genre', models.CharField(blank=True, help_text='The global classification for the given artist', max_length=100, null=True)),
                ('spotify_avatar', models.URLField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
