# Generated by Django 5.1.4 on 2025-02-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_alter_artist_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='spotify_avatar',
        ),
        migrations.RemoveField(
            model_name='song',
            name='spotify_id',
        ),
    ]
