# Generated by Django 5.1.4 on 2025-03-15 11:26

import songs.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_remove_song_artist_name_artist_birthname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='wikipedia_page',
            field=models.URLField(blank=True, null=True, validators=[songs.validators.validate_wikipedia_page]),
        ),
    ]
