# Generated by Django 5.2.7 on 2025-10-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_artist_wikipedia_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopArtist',
            fields=[
            ],
            options={
                'ordering': ['birthname'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('songs.artist',),
        ),
        migrations.CreateModel(
            name='RapArtist',
            fields=[
            ],
            options={
                'ordering': ['birthname'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('songs.artist',),
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['name'], 'verbose_name': 'artist'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['artist'], 'verbose_name': 'song'},
        ),
        migrations.AddField(
            model_name='artist',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="The artist's birth name or the date of formation if a group", null=True),
        ),
    ]
