# Generated by Django 5.2.8 on 2026-01-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0008_alter_song_difficulty_alter_song_year_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                condition=models.Q(("difficulty", 1)),
                fields=["difficulty"],
                name="difficulty_easy",
            ),
        ),
    ]
