# Generated by Django 5.2.8 on 2026-01-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0009_song_difficulty_easy"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(
                condition=models.Q(("is_group", True)),
                fields=["is_group"],
                name="musical_groups",
            ),
        ),
    ]
