<template>
  <div class="col-span-12">
    <volt-card>
      <template #content>
        <div class="flex gap-2">
          <volt-button :variant="selectedTeam===1 ? 'primary' : 'outlined'" @click="selectedTeam=1">
            Team 1
          </volt-button>

          <volt-button :variant="selectedTeam===2 ? 'primary' : 'outlined'" @click="selectedTeam=2">
            Team 2
          </volt-button>
        </div>

        <div class="flex justify-center my-10">
          {{ debouncedWheelColor }}
          <vue-color-wheel v-model:color="wheelColor" wheel="aurora" harmony="complementary" :radius="160" :default-color="wheelColor" @change="handleChangeColor" />
        </div>

        <volt-input-text v-model="wheelColor" />
      </template>
    </volt-card>
  </div>
</template>

<script setup lang="ts">
import type { Harmony } from 'vue-color-wheel'
import { VueColorWheel } from 'vue-color-wheel'

const colorList = ref<Harmony[]>()
const wheelColor = shallowRef('#5a228b')
const debouncedWheelColor = refDebounced(wheelColor, 1000)

/**
 * Function to handle the change of color in the color wheel
 * @param harmonyColors The list of harmony colors generated by the color wheel
 */
function handleChangeColor(harmonyColors: Harmony[]) {
  colorList.value = harmonyColors
}

const selectedTeam = ref<number>(1)

const teamStore = useTeamsStore()
const { teamOne, teamTwo, teams } = storeToRefs(teamStore)

watch(wheelColor, (newValue) => {
  if (selectedTeam.value === 1) {
    if (teamOne.value) {
      teamOne.value.color = newValue
    }
  } else {
    if (teamTwo.value) {
      teamTwo.value.color = newValue
    }
  }
})
</script>
