<template>
  <section class="w-4xl mx-auto px-10 my-20 relative">
    <div class="grid grid-cols-12 gap-2 my-10">
      <div class="col-span-12">
        <VoltCard>
          <template #content>
            <div class="space-x-2 flex justify-between">
              <VoltButton rounded>
                <VueIcon icon="fa-solid:arrow-left" />
                <RouterLink :to="{ name: 'home' }">
                  Back to settings
                </RouterLink>
              </VoltButton>

              <VoltButton rounded>
                <RouterLink :to="{ name: 'blind_test' }">
                  Go to blindtest
                </RouterLink>
                <VueIcon icon="fa-solid:arrow-right" />
              </VoltButton>
            </div>
          </template>
        </VoltCard>
      </div>

      <div class="col-span-6">
        <VoltCard>
          <template #content>
            <VoltInputText v-model="teamOne.name" placeholder="Team name" />
          </template>
        </VoltCard>
      </div>

      <div class="col-span-6">
        <VoltCard>
          <template #content>
            <VoltInputText v-model="teamTwo.name" placeholder="Team name" />
          </template>
        </VoltCard>
      </div>

      <div class="col-span-12">
        <VoltCard>
          <template #content>
            <div class="flex gap-2">
              <VoltButton :active="selectedTeam===1" @click="selectedTeam=1">
                Team 1
              </VoltButton>

              <VoltButton :active="selectedTeam===2" @click="selectedTeam=2">
                Team 2
              </VoltButton>
            </div>

            <div class="flex justify-center my-10">
              {{ debouncedWheelColor }}
              <VueColorWheel v-model:color="wheelColor" wheel="aurora" harmony="complementary" :radius="160" :default-color="wheelColor" @change="handleChangeColor" />
            </div>

            <VoltInputText v-model="wheelColor" />
          </template>
        </VoltCard>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { VueColorWheel } from 'vue-color-wheel'

import type { Harmony } from 'vue-color-wheel'

// const wheelColor = useDebounce(ref<string>('#5a228b'))

const selectedTeam = ref(1)
const colorList = ref<Harmony[]>()
const wheelColor = shallowRef('#5a228b')
const debouncedWheelColor = refDebounced(wheelColor, 1000)

/**
 * Functin to handle the change of color in the color wheel
 * @param harmonyColors The list of harmony colors generated by the color wheel
 */
function handleChangeColor(harmonyColors: Harmony[]) {
  colorList.value = harmonyColors
}

const teamStore = useTeamsStore()
const { teamOne, teamTwo, teams } = storeToRefs(teamStore)

watch(wheelColor, (newValue) => {
  if (selectedTeam.value === 1) {
    teams.value[0].color = newValue
  } else {
    teams.value[1].color = newValue
  }
})

// const songsStore = useSongs()
// const teamOne = computed(() => {
//   return songsStore.cache.teams[0]
// })

// const teamTwo = computed(() => {
//   return songsStore.cache.teams[1]
// })

useHead({
  title: 'Settings'
})
</script>
