<template>
  <section class="w-4xl mx-auto px-10 my-20 relative">
    <div class="grid grid-cols-12 gap-2 my-10">
      <div class="col-span-12">
        <volt-card>
          <template #content>
            <div class="space-x-2 flex justify-between">
              <volt-secondary-button rounded>
                <vue-icon icon="fa-solid:arrow-left" />
                <router-link :to="{ name: 'home' }">
                  Back to settings
                </router-link>
              </volt-secondary-button>

              <volt-secondary-button rounded>
                <router-link :to="{ name: 'blind_test' }">
                  Go to blindtest
                </router-link>
                <vue-icon icon="fa-solid:arrow-right" />
              </volt-secondary-button>
            </div>
          </template>
        </volt-card>
      </div>

      <div class="col-span-6">
        <volt-card>
          <template #content>
            <volt-input-text v-if="teamOne" v-model="teamOne.name" class="w-full" placeholder="Team name" />
          </template>
        </volt-card>
      </div>

      <div class="col-span-6">
        <volt-card>
          <template #content>
            <volt-input-text v-if="teamTwo" v-model="teamTwo.name" class="w-full" placeholder="Team name" />
          </template>
        </volt-card>
      </div>

      <div class="col-span-12">
        <volt-card>
          <template #content>
            <div class="flex gap-2">
              <volt-button :variant="selectedTeam===1 ? 'primary' : 'outlined'" @click="selectedTeam=1">
                Team 1
              </volt-button>

              <volt-button :variant="selectedTeam===2 ? 'primary' : 'outlined'" @click="selectedTeam=2">
                Team 2
              </volt-button>
            </div>

            <div class="flex justify-center my-10">
              {{ debouncedWheelColor }}
              <vue-color-wheel v-model:color="wheelColor" wheel="aurora" harmony="complementary" :radius="160" :default-color="wheelColor" @change="handleChangeColor" />
            </div>

            <volt-input-text v-model="wheelColor" />
          </template>
        </volt-card>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { VueColorWheel } from 'vue-color-wheel'

import type { Harmony } from 'vue-color-wheel'

const colorList = ref<Harmony[]>()
const wheelColor = shallowRef('#5a228b')
const debouncedWheelColor = refDebounced(wheelColor, 1000)

/**
 * Function to handle the change of color in the color wheel
 * @param harmonyColors The list of harmony colors generated by the color wheel
 */
function handleChangeColor(harmonyColors: Harmony[]) {
  colorList.value = harmonyColors
}

const selectedTeam = ref<number>(1)

const teamStore = useTeamsStore()
const { teamOne, teamTwo, teams } = storeToRefs(teamStore)

watch(wheelColor, (newValue) => {
  if (selectedTeam.value === 1) {
    if (teamOne.value) {
      teamOne.value.color = newValue
    }
  } else {
    if (teamTwo.value) {
      teamTwo.value.color = newValue
    }
  }
})

useHead({
  title: 'Settings'
})
</script>
