import { faA, faArrowLeft, faArrowRight, faBars, faBolt, faBrush, faChartSimple, faCheck, faCog, faForward, faHome, faPen, faPeopleGroup, faPlay, faPlus, faRefresh, faShuffle, faStop, faT, faXmark } from '@fortawesome/free-solid-svg-icons'
import { library } from '@fortawesome/fontawesome-svg-core'

library.add(faPlay)
library.add(faForward)
library.add(faShuffle)
library.add(faRefresh)
library.add(faStop)
library.add(faCheck)
library.add(faXmark)
library.add(faCog)
library.add(faPeopleGroup)
library.add(faChartSimple)
library.add(faBars)
library.add(faPlus)
library.add(faBrush)
library.add(faPen)
library.add(faBolt)
library.add(faArrowLeft)
library.add(faArrowRight)
library.add(faHome)
library.add(faA)
library.add(faT)
