# Generated by Django 5.2.6 on 2025-11-21 19:33

import blindtest.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0007_afrosong'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThemeSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField(default=0, validators=[blindtest.validators.validate_year])),
                ('created_on', models.DateField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.artist')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshows.tvshow')),
            ],
            options={
                'ordering': ['series', 'artist'],
                'constraints': [models.UniqueConstraint(fields=('series', 'name'), name='unique_theme_song_per_series')],
            },
        ),
    ]
