# Generated by Django 5.2.6 on 2025-11-21 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_afrosong'),
        ('tvshows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesong',
            name='youtube_id',
            field=models.CharField(default='5-xnvdtuRRo', help_text='The YouTube video ID for the theme song', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='themesong',
            name='artist',
            field=models.ForeignKey(blank=True, help_text='The artist who performed the theme song if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='songs.artist'),
        ),
        migrations.AlterField(
            model_name='themesong',
            name='name',
            field=models.CharField(blank=True, help_text='If the theme song has a specific name, enter it here', max_length=200, null=True),
        ),
    ]
