# Generated by Django 5.2.6 on 2025-11-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0003_themesong_difficulty_themesong_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='title',
            field=models.CharField(help_text='The title of the television series', max_length=200, unique=True),
        ),
    ]
