# Generated by Django 5.2.6 on 2025-11-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0004_alter_tvshow_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='title_fr',
            field=models.CharField(blank=True, help_text='The French title of the television series, if applicable', max_length=200, null=True),
        ),
    ]
