# Generated by Django 5.2.7 on 2025-11-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvshows", "0006_remove_themesong_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="tvshow",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to an image representing the television series",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="imdb_id",
            field=models.CharField(
                blank=True,
                help_text="The IMDB identifier for the television series",
                max_length=20,
                null=True,
                unique=True,
            ),
        ),
    ]
